plugins {
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.jetbrains.kotlin.jvm' version '2.0.21'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.0.21'
    id 'org.jetbrains.kotlin.plugin.jpa' version '2.0.21'
}

group = 'com.perfo'
version = '0.2.0-rc.19'

springBoot {
    mainClass = 'com.perfo.backend.BackendApplicationKt'
}

kotlin {
    jvmToolchain(17)
}

repositories {
    mavenCentral()
}

configurations.configureEach {
    resolutionStrategy {
        force 'com.squareup.okhttp3:okhttp-jvm:4.12.0'
        force 'com.squareup.okhttp3:logging-interceptor-jvm:4.12.0'
        force 'com.squareup.okio:okio-jvm:3.6.0'
    }
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // Database
    runtimeOnly 'org.postgresql:postgresql'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // Swagger (springdoc-openapi)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
    implementation 'io.minio:minio:8.5.17'

    // Kotlin
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.4.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // H2 in-memory DB for integration tests
    testRuntimeOnly 'com.h2database:h2'

}

tasks.named('test') {
    useJUnitPlatform()
    jvmArgs '-Xshare:off'
}
