create table if not exists ticketing_outbox (
    id bigint generated by default as identity primary key,
    request_id varchar(120) not null unique,
    event_id bigint not null,
    user_id bigint not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(120) not null,
    event_type varchar(64) not null,
    status varchar(32) not null,
    payload text not null,
    retry_count integer not null default 0,
    published_at timestamp(6),
    last_error varchar(1000),
    created_at timestamp(6),
    updated_at timestamp(6)
);

create index if not exists idx_ticketing_outbox_status_created
    on ticketing_outbox (status, created_at);
