begin;

alter table events
    add column if not exists booking_mode varchar(32) not null default 'SIMPLE';

alter table issued_tickets
    add column if not exists booking_mode varchar(32) not null default 'SIMPLE';

create table if not exists event_items (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    name varchar(120) not null,
    description varchar(1000),
    image_url varchar(1000),
    price integer,
    total_quantity integer not null,
    remaining_quantity integer not null,
    max_per_user integer not null,
    active boolean not null,
    sort_order integer not null
);

create index if not exists idx_event_items_event_sort
    on event_items (event_id, sort_order, id);

create table if not exists booking_drafts (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id bigint not null,
    version integer not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_booking_drafts_event_user unique (event_id, user_id)
);

create table if not exists booking_draft_items (
    id bigint generated by default as identity primary key,
    draft_id bigint not null,
    event_item_id bigint not null,
    quantity integer not null,
    constraint uk_booking_draft_items_draft_item unique (draft_id, event_item_id)
);

create index if not exists idx_booking_draft_items_draft
    on booking_draft_items (draft_id);

create table if not exists booking_orders (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id bigint not null,
    request_id varchar(120) not null unique,
    status varchar(32) not null,
    created_at timestamp(6)
);

create index if not exists idx_booking_orders_event_user
    on booking_orders (event_id, user_id);

create table if not exists booking_order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    event_item_id bigint not null,
    item_name_snapshot varchar(120) not null,
    quantity integer not null
);

create index if not exists idx_booking_order_items_order
    on booking_order_items (order_id);

create index if not exists idx_booking_order_items_event_item
    on booking_order_items (event_item_id);

alter table ticketing_requests
    add column if not exists booking_mode varchar(32) not null default 'SIMPLE',
    add column if not exists items_snapshot text,
    add column if not exists shortages_snapshot text;

alter table ticketing_purchase_projection
    add column if not exists booking_mode varchar(32) not null default 'SIMPLE',
    add column if not exists order_items text;

commit;
