-- Phase 1 ticketing engine explicit schema migration for PostgreSQL.
-- First production rollout should run with SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
-- and SPRING_JPA_HIBERNATE_DDL_AUTO=validate.

begin;

alter table events
    add column if not exists sale_open_at timestamptz,
    add column if not exists sale_close_at timestamptz,
    add column if not exists allow_duplicate boolean,
    add column if not exists next_ticket_number integer;

update events
set sale_open_at = coalesce(sale_open_at, valid_from at time zone 'Asia/Seoul'),
    sale_close_at = coalesce(sale_close_at, valid_until at time zone 'Asia/Seoul'),
    allow_duplicate = coalesce(allow_duplicate, false),
    next_ticket_number = coalesce(
        next_ticket_number,
        greatest(
            1,
            coalesce(
                (
                    select max(t.ticket_number) + 1
                    from tickets t
                    where t.event_id = events.id
                ),
                1
            )
        )
    );

alter table events
    alter column sale_open_at set not null,
    alter column sale_close_at set not null,
    alter column allow_duplicate set not null,
    alter column next_ticket_number set not null;

create table if not exists ticketing_requests (
    id bigint generated by default as identity primary key,
    request_id varchar(120) not null unique,
    event_id bigint not null,
    user_id bigint not null,
    quantity integer not null,
    result varchar(64) not null,
    ticket_ids varchar(1000),
    ticket_numbers varchar(1000),
    remaining_quantity integer,
    message varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6)
);

create index if not exists idx_ticketing_requests_event_user
    on ticketing_requests (event_id, user_id);

commit;
