create table if not exists ticketing_purchase_projection (
    id bigint generated by default as identity primary key,
    outbox_id bigint not null unique,
    request_id varchar(120) not null,
    event_id bigint not null,
    user_id bigint not null,
    event_type varchar(64) not null,
    result varchar(64) not null,
    quantity integer not null,
    ticket_ids varchar(1000),
    ticket_numbers varchar(1000),
    remaining_quantity integer,
    message varchar(255),
    occurred_at timestamp with time zone not null,
    projected_at timestamp(6)
);

create index if not exists idx_ticketing_purchase_projection_event
    on ticketing_purchase_projection (event_id, occurred_at);
